default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: always_development

test:
  <<: *default
  database: always_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: always_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
